# Generated by Django 5.1.2 on 2024-10-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookTitle',
            new_name='title',
        ),
    ]
